bot_user_id = '@newsbot:ansible.im'
reporting_room_id = '!pMZboYFCScZJfXmOtH:ansible.im'
admin_room_id = '!ksnKLXrvVRKHhYGMFg:ansible.im'
notice_emoji = 'â­•'   # :o:
image_emoji = 'ğŸ“·ï¸'    # :camera:
video_emoji = 'ğŸ“¹ï¸'    # :video_camera:
image_markdown = '> ![](/post/bullhorn/{{file}})'
video_markdown = '> {{< video src="/post/bullhorn/{{file}}" >}}'
update_config_command = "sh /data/update_config.sh"
editors = [
    '@cybette:ansible.im',
    '@gundalow:ansible.im',
    '@gwmngilfen:ansible.im',
    '@dmsimard:matrix.org',
    '@cybette:matrix.org',
    '@samccann:ansible.im',
    '@andersson007_:matrix.org',
    '@deric.crago:ansible.im',
    '@ompragash:ansible.im'
]

[[sections]]
emoji = 'â±ï¸' # :stopwatch:
name = 'dates'
title = 'KEY DATES'
order = 100
usual_reporters = []

[[sections]]
emoji = 'ğŸ”ˆï¸' # :speaker:
name = 'general'
title = 'GENERAL NEWS UPDATES'
order = 101
usual_reporters = []

[[sections]]
emoji = 'ğŸ†ï¸' # :trophy:
name = 'releases'
title = 'MAJOR NEW RELEASES'
order = 102
usual_reporters = []

[[sections]]
emoji = 'ğŸª„' # :magic_wand:
name = 'collections'
title = 'COLLECTION UPDATES'
order = 103
usual_reporters = []

[[sections]]
emoji = 'ğŸ™' # :pray:
name = 'help'
title = 'HELP WANTED'
order = 104
usual_reporters = []

[[sections]]
emoji = 'ğŸ—³ï¸' # :ballot_box:
name = 'proposals'
title = 'PROPOSALS - DISCUSS AND VOTE!'
order = 105
usual_reporters = []

[[sections]]
emoji = 'ğŸ‘‚ï¸' # :ear:
name = 'community'
title = 'COMMUNITY UPDATES'
order = 106
usual_reporters = []

[[sections]]
emoji = 'ğŸ“…' # :date:
name = 'events'
title = 'COMMUNITY EVENTS AND MEETUPS'
order = 107
usual_reporters = []

[[sections]]
emoji = 'ğŸ’°ï¸' # :moneybag:
name = 'hiring'
title = 'THE ANSIBLE TEAM IS HIRING'
order = 108
usual_reporters = []

[[projects]]
emoji = 'ğŸªœ' # :ladder:
name = 'maintainers'
title = 'Maintainers'
description = 'Maintainers help to run the community!'
website = 'https://github.com/ansible-community'
default_section = 'community'
usual_reporters = []

[[projects]]
emoji = 'âš¡ï¸' # :zap:
name = 'core'
title = 'Ansible-Core'
description = "The `ansible-core` package contains the base engine and a small subset of modules and plugins. To see what's planned for the next release, look at the [`ansible-core` roadmaps](https://docs.ansible.com/ansible-core/devel/roadmap/ansible_core_roadmap_index.html)."
website = 'https://github.com/ansible/ansible'
default_section = 'releases'
usual_reporters = []

[[projects]]
emoji = 'ğŸ“¦ï¸' # :package:
name = 'ansible'
title = 'Ansible'
description = "The `Ansible` package includes `ansible-core` and is a batteries-included package that provides a curated set of Ansible collections. See the [Ansible roadmaps](https://docs.ansible.com/ansible/devel/roadmap/ansible_roadmap_index.html) for future release plans."
website = 'https://github.com/ansible-collections'
default_section = 'releases'
usual_reporters = []

[[projects]]
emoji = 'â›ï¸' # :pick:
name = 'devtools'
title = 'DevTools'
description = "Projects to make it easier to write and test Ansible Content. Includes [VScode extension](https://github.com/ansible/vscode-ansible), [language server](https://github.com/ansible/ansible-language-server), [ansible-lint](https://github.com/ansible-community/ansible-lint), [molecule](https://github.com/ansible-community/molecule), [ansible-navigator](https://github.com/ansible/ansible-navigator) and potentially other development goodies. To see what's planned, and how you can help checkout the [foundation-devtools project board](https://github.com/orgs/ansible/projects/86/views/4)"
website = 'https://github.com/ansible/vscode-ansible'
default_section = 'releases'
usual_reporters = []

[[projects]]
emoji = 'ğŸ‚' # :ox:
name = 'antsibull'
title = 'Antsibull'
description = "Tooling for building the `Ansible` package and collection documentation."
website = 'https://github.com/ansible-community/antsibull'
default_section = 'releases'
usual_reporters = []
