bot_user_id = '@newsbot:ansible.im'
reporting_room_id = '!cWHikIGOAhtEmFDdoH:matrix.org'
admin_room_id = '!ksnKLXrvVRKHhYGMFg:ansible.im'
notice_emoji = 'â­•'   # :o:
image_emoji = 'ğŸ“·ï¸'    # :camera:
video_emoji = 'ğŸ“¹ï¸'    # :video_camera:
image_markdown = '> ![](/post/bullhorn/{{file}})'
video_markdown = '> {{< video src="/post/bullhorn/{{file}}" >}}'
update_config_command = "sh /data/update_config.sh"
editors = [
    '@cybette:ansible.im',
    '@gundalow:ansible.im',
    '@gwmngilfen:ansible.im',
    '@dmsimard:matrix.org',
    '@cybette:matrix.org',
]

[[sections]]
emoji = 'â±ï¸' # :stopwatch:
name = 'dates'
title = 'KEY DATES'
order = 100
usual_reporters = []

[[sections]]
emoji = 'ğŸ”ˆï¸' # :speaker:
name = 'general'
title = 'GENERAL NEWS UPDATES'
order = 101
usual_reporters = []

[[sections]]
emoji = 'ğŸ†ï¸' # :trophy:
name = 'releases'
title = 'MAJOR NEW RELEASES'
order = 102
usual_reporters = []

[[sections]]
emoji = 'ğŸª„' # :magic_wand:
name = 'collections'
title = 'COLLECTION UPDATES'
order = 103
usual_reporters = []

[[sections]]
emoji = 'ğŸ‘‚ï¸' # :ear:
name = 'community'
title = 'COMMUNITY UPDATES'
order = 104
usual_reporters = []

[[sections]]
emoji = 'ğŸ“…' # :date:
name = 'events'
title = 'COMMUNITY EVENTS/MEETUPS'
order = 105
usual_reporters = []

[[sections]]
emoji = 'ğŸ’°ï¸' # :moneybag:
name = 'hiring'
title = 'THE ANSIBLE TEAM IS HIRING'
order = 106
usual_reporters = []

[[projects]]
emoji = 'ğŸªœ' # :ladder:
name = 'maintainers'
title = 'Maintainers'
description = 'Maintainers help to run the community!'
website = 'https://github.com/ansible-community'
default_section = 'community'
usual_reporters = []

[[projects]]
emoji = 'âš¡ï¸' # :zap:
name = 'core'
title = 'Ansible-Core'
description = '**Ansible Core** is minimal package containing the base engine, modules, and plugins'
website = 'https://github.com/ansible/ansible'
default_section = 'releases'
usual_reporters = []

[[projects]]
emoji = 'ğŸ“¦ï¸' # :package:
name = 'ansible'
title = 'Ansible'
description = '**Ansible** is the full-fat package containing Ansible Core & the Community Collections'
website = 'https://github.com/ansible-collections'
default_section = 'releases'
usual_reporters = []

[[projects]]
emoji = 'â›ï¸' # :pick:
name = 'devtools'
title = 'DevTools'
description = 'VScode extension, language server, linter, molecule, runner, navigator and potentially other development goodies'
website = 'https://github.com/ansible/vscode-ansible'
default_section = 'releases'
usual_reporters = []


[[projects]]
emoji = 'ğŸ‚' # :ox:
name = 'antsibull'
title = 'Antsibull'
description = 'Tooling for building various things related to ansible'
website = 'https://github.com/ansible-community/antsibull'
default_section = 'releases'
usual_reporters = []
